import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import Link from "next/link";
import { treatments } from "@/data/treatments";

{/* <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect width="100" height="100" rx="20" fill="#ec4899"/>
  <text
    x="50"
    y="65"
    text-anchor="middle"
    font-size="64"
    fill="white"
    font-family="Bad Script, cursive"
  >
    
  </text>
</svg> */}

export const metadata: Metadata = {
  title: "Aura",
  description: "Generated by create next app",
  icons: {
    icon: '/favico.svg',
  },

};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="es">
      <body>
        <header className="bg-pink-600 text-white p-4">
          <nav className="flex flex-wrap gap-4 justify-center font-semibold">
            <Link href="/">Inicio</Link>
            {treatments.map((t) => (
              <Link key={t.slug} href={`/${t.slug}`}>
                {t.title}
              </Link>
            ))}
          </nav>
        </header>

        {children}

        <footer className="bg-gray-100 text-center p-4 text-sm text-gray-500">
          © 2026 Aura · Todos los derechos reservados
        </footer>
      </body>
    </html>
  );
}




